import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { FitLogProvider } from "@/context/FitLogContext";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Fit Log App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">
        <FitLogProvider>
          <Navbar />

          <main className="flex-1">{children}</main>

          <Footer />

          <Toaster position="top-right" />
        </FitLogProvider>
      </body>
    </html>
  );
}
